bowling object 課題
smallmonkeykey/ruby-practices pull request #10
Opened 2024-01-31 07:54 UTC by smallmonkeykey

2024-02-10 04:00 UTC, u1tnk requested changes
コメントは多いですが、結構シンプルに書けているので、細かめの指摘をしています 👍

2024-02-10 04:00 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +  def sum_score
`frame.score` とあれば そのフレームの合計スコアであろう事は自明なので sumは不要そうです。
ただ、これは ボーナススコアを除いたものに見えますので、そこが分かる名前にすると良いと思います。

2024-02-10 04:00 UTC, u1tnk commented on 06.bowling_object/game_test.rb
> +  def test_game1
プラクティスはテスト必須でも無いし現状これで良いですが、 `test_perfect`のようにタイトルで分かるとより良いですね。

2024-02-10 04:00 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  def initialize(result)
resultは抽象的過ぎるので具体的に何が入ってるか分かる名前にしましょう。

2024-02-10 04:00 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  def calculate_total_score
ここも gameのscoreと書いてあれば合計と思うので totalは不要かと思います。
calculateは持ってるものを返すだけじゃないよ！というニュアンスがあるのであった方が良いかと思いますが、無くてもダメというほどじゃないです。

2024-02-10 04:00 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  def calculate_normal_frame(frame, index, totals)
この引数で渡して中身で書き替えるというパターンはどこで更新しているか分かりづらいので避けた方が良いですね。totalを返せば問題無いと思いますし。
渡さなくて良い引数は減らした方が良いという理由もあります。

2024-02-10 04:00 UTC, u1tnk commented on 06.bowling_object/game.rb
> +        scores.unshift(rolls.last)
元の配列を壊して二個取って不要なら返すというのはちょっと気持ち悪いです。
ダメじゃないけど、何かうまくいかなかったら混乱しがちなので。
なるべく非破壊的に処理したいですが、このケースは破壊的な方がシンプルになりそうなので破壊的なのは良いですが、減らす方向だけにしたいですね。

2024-02-10 04:08 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +  attr_reader :first_shot, :second_shot, :third_shot
third_shotは参照されることが無いと思います。
全部に無いと気持ち悪いとは思うのですが、、オブジェクト内部へのアクセスは最小限にするのが良いですね。

2024-02-10 04:10 UTC, u1tnk commented on 06.bowling_object/game.rb
> +    @scores = result.split(',')
scoreという名前と中身が一致していないと思います。

2024-02-10 04:11 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  attr_reader :scores, :frames
この二つはアクセスされる必要は無いと思います。
内部からのアクセスであれば `@xxx`を使いましょう。内部データだということがはっきりします。

2024-02-14 00:40 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +        scores.unshift(rolls.last)
違和感があるコードを書いてすいません😢
非破壊的な処理に変更しました！
[538e3fa](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/538e3fa19472716e3e9dd9c6a9d3a3d667c0a432)

2024-02-14 00:58 UTC, smallmonkeykey commented on 06.bowling_object/game_test.rb
> +  def test_game1
おお！` test_perfect`のようなタイトルだと、何をテストしているかがわかりやすいですね！
教えてくださり、ありがとうございます！
 [964e83b](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/964e83bb72a7648811b7b336d79d2f544f95523b)

2024-02-14 01:48 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +  def initialize(result)
`user_input`という変数名に変更しました。
[36538ad](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/36538ad9d65c707c5abbbb19c509437b5f046576)

2024-02-14 01:58 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +    @scores = result.split(',')
`user_input`の、配列なので`user_inputs`にしました。
[a0abfc3](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/a0abfc36db2dd14a22583ed97145f41b04821538)

2024-02-14 02:02 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +  def calculate_total_score
命名する時に、totalを入れるか迷ったのですが結局いれてしまいました。
コメントくださってスッキリしました。ありがとうございます。

削除しました！
[112248f](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/112248febcbf5a25d1e9d23985aa1d025e0db603)

2024-02-14 02:12 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +  attr_reader :scores, :frames
修正しました！[43a079b](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/43a079b0fae7c1b407161148f77a56e1ad70a32c)

2024-02-14 02:16 UTC, smallmonkeykey commented on 06.bowling_object/frame.rb
> +  attr_reader :first_shot, :second_shot, :third_shot
まさに全部にないと変かな…と思い、attr_reader してしまいました。
参照されないものは、@ にします！

2024-02-14 05:24 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +  def calculate_normal_frame(frame, index, totals)
教えてくださり、ありがとうございます。
アドバイスのおかげで、みやすいコードになりました！

[8c82a1b](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/8c82a1b0ab4979eb30ff5b27fc397d3d991daa22)

2024-02-14 08:25 UTC, smallmonkeykey commented on 06.bowling_object/frame.rb
> +  def sum_score
`normal_score`に変更しました！
[25a8c2e](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/25a8c2e430f08e0b62aa82751ee2cf4477ab164b)

2024-02-14 16:27 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +  def sum_score
normalでbonusが無いというのは分かる気はしますが…微妙なところですね。
 `score_without_bonus` ぐらい冗長でもはっきいと意図が分かる名前が良いと思います。
もうちょっとシンプルで分かる名前が良いですが思いつかないです。

2024-02-14 16:28 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  def initialize(result)
良いと思います 🙆‍♀️ 
marksだと markの配列っぽいですね。他だと Gameに渡す前に splitだけしておいて marksとするパターンもありますね。

2024-02-14 16:30 UTC, u1tnk commented on 06.bowling_object/game.rb
> +        scores.unshift(rolls.last)
レビューの技術的な指摘に対しては謝る必要は無いですよ！
その違和感を身につけるためのプラクティスなので。

2024-02-14 16:35 UTC, u1tnk commented on 06.bowling_object/game.rb
> +    @scores = result.split(',')
user_inputがたくさんあるわけでは無いのでちょっとおかしいと思います。
frameが入っている配列は famesですが、このframesは frameを分割したわけじゃないですよね？
user_inputを分割してShotに渡してると思いますが、そこでは何と呼んでいますか？
同じものは同じ名前で呼ぶようにしましょう。

2024-02-14 16:47 UTC, u1tnk requested changes
もうちょっとですね！
Gameのscore計算のところは変更必須では無いのでチャレンジするかはお任せします。

2024-02-14 16:47 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +  STRIKE = 10
ちょっと細かいですが、STRIKEの何かまで書いて欲しいです。数字を見たら分かりますが、使われるときは定数名しか見えないのでそこで分かる名前が必要です。

2024-02-14 16:47 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    first_shot.score + second_shot.score == 10
STRIKEは10にしているのにここは数値そのまま使っているのは良くないですね。

2024-02-14 16:47 UTC, u1tnk commented on 06.bowling_object/game.rb
> +    @frames << Frame.new(*@user_inputs[i..])
ここの引数渡しはちょっと難しいと思いますがよく書けましたね 👍

2024-02-14 16:47 UTC, u1tnk commented on 06.bowling_object/game.rb
> +        i += 1
非破壊的に書けていますね 👍

2024-02-14 16:47 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    first_shot.score + second_shot.score == 10
これ、strikeのときもtrueが返るのは良くないですね。

2024-02-14 16:47 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  def calculate_normal_frame(frame, index)
プラクティス的に書き替えまではしなくて良いですが、
もしよりオブジェクト指向らしく、すっきりと書きたいのであれば、このメソッドをFrameに移動すると良いかと思います。
足りない情報があるのでGameでやっていると思いますが、initializeに入れるか引数で渡すかするばFrame側で参照することは可能です。

2024-02-15 04:46 UTC, smallmonkeykey commented on 06.bowling_object/frame.rb
> +  def sum_score
なるほど！それくらい意図がわかるようにしないといけないんですね。
今回は教えていただいた`score_without_bonus`にしました。
[562e29b](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/562e29b7b04a89bc3cf46c87635c6a72fb004aa1)

2024-02-15 05:36 UTC, smallmonkeykey commented on 06.bowling_object/frame.rb
> +  STRIKE = 10
`STRIKE_SCORE`に変更しました！
[beb7e35](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/beb7e354e398dae0d2cb0400382dbb8956f3d0b9)

2024-02-15 05:50 UTC, smallmonkeykey commented on 06.bowling_object/frame.rb
> +    first_shot.score + second_shot.score == 10
気づきませんでした😨
教えてくださり、ありがとうございます。
[0a6abdb](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/0a6abdb6c097cfd8be6532f15b50cc12710aa6b3)

2024-02-15 05:52 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +        i += 1
思いつくまでに2日かかったので、嬉しいです！ありがとうございます！

2024-02-15 06:12 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +    @scores = result.split(',')
> user_inputを分割してShotに渡してると思いますが、そこでは何と呼んでいますか？

marksに変更しました！

> 同じものは同じ名前で呼ぶようにしましょう

こちらの意識がたりなかったです。教えてくださってありがとうございます🙏
[16b66bb](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/16b66bbb9f319298a190e7a2ba9a50e878193a5b)

2024-02-15 06:15 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +  def initialize(result)
>  Gameに渡す前に splitだけしておいて marksとするパターンもありますね。

こちらの方が、initializeメソッドがすっきりするため、先にsplitにしてmarksとして渡すように変更しました。
[16b66bb](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/16b66bbb9f319298a190e7a2ba9a50e878193a5b)

2024-02-15 13:41 UTC, smallmonkeykey commented on 06.bowling_object/game.rb
> +  def calculate_normal_frame(frame, index)
Frameに移動しました！引数で渡しました。

[d3be5eb](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/d3be5eb6c72693207206c86f64083d708999320c)

2024-02-15 16:56 UTC, u1tnk approved these changes
一件コメントしましたがかなり細かいので 合格とします 🙆‍♀️

2024-02-15 16:56 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    !strike? && first_shot.score + second_shot.score == STRIKE_SCORE
SPARE_SCORE を作らないのであれば名前は工夫したいですね。
STRIKE_OR_SPARE_SCORE

でもよしです。もちろんちょっと冗長なので一工夫は欲しいです。
MAX_SCOREとかアリかなー 🤔

2024-02-16 03:22 UTC, smallmonkeykey commented on 06.bowling_object/frame.rb
> +    !strike? && first_shot.score + second_shot.score == STRIKE_SCORE
同じ数字の10ということに引っ張られてしまって、定数を一つにしなければならないと思い込んでしまっていました。
`SPARE_SCORE`を作成しました。

[c162366](https://github.com/smallmonkeykey/ruby-practices/pull/10/commits/c1623665f4b3ff5ea67b8865d306fb71d990cb3b)

2024-02-29 13:21 UTC, merged